### ISSUE TITLE
Beautify leaves huge gaps with .onSave option on.

### ISSUE THREAD

**Issue by sqnkov** [HookyQR/VSCodeBeautify#73] opened 2016-11-27 09:59 UTC
After the latest update that requires the ```"editor.formatOnSave": true``` , vs code leaves huge gaps within my code and it does so at random saves. Any other configuration tips that I need to be aware of? This was not an issue before the update.

![beatufity_issue](https://cloud.githubusercontent.com/assets/9406520/20647279/edcc62bc-b498-11e6-99f9-96a9f8188453.PNG)

Problem is only present if ```editor.formatOnSave``` is active, but then the beautifying doesn't work.

**Comment by HookyQR** [comment] 2016-11-27 17:08
I'm going to assume you're on a windows machine and your line endings (when editing the files you show) are set to LF in the editor. If you have a `.jsbeautifyrc` file, add `"eol": "\n"`, if not, add `"files.eol": "\n"` to your VS Code settings.

This is a known issue, but there is a fix coming in the 1.8.0 release of VS Code.

**Comment by HookyQR** [comment] 2016-11-27 17:27
I've release 0.6.1 to hopefully return the previous functionality. Let me know how that goes.

**Comment by sqnkov** [comment] 2016-11-27 22:17
Just updated to ```0.6.1```, nothing has changed.

**Comment by HookyQR** [comment] 2016-11-28 03:54
Hey @sqnkov, I don't have a PC with me ATM, to improve the speed of resolution, can you please provide the following files/details:
Any format setting files [`.jsbeautifyrc`, `.editorconfig`, `.vscode/settings.json` (or your global settings file if you're not using a workspace settings file)]

What the editor is showing as the end of line setting (LF or CRLF) which will be on the status bar at the bottom left of the window.

**Comment by HookyQR** [comment] 2016-11-28 04:24
Have released 0.6.2. Again, this _should_ fix it. Let me know how you go.

**Comment by jeremysu0131** [comment] 2016-11-28 06:11
Hello, 0.6.2 can work!
But,if i set `"editor.formatOnSave": true` it showing this:

> Incorrect type. Expected one of array
> Use array to set indiviaul types to beautify: ["js", "html", "css"]. Requires "editor.formatOnSave" to be true.

Just change `"editor.formatOnSave": true` to `"beautify.onSave": ["js", "html", "css"]` ,and it will works!

**Comment by sqnkov** [comment] 2016-11-28 09:46
Just updated to ```0.6.2``` , beautify on save is not working.

These are my only settings:

![curset](https://cloud.githubusercontent.com/assets/9406520/20663440/2a74fae0-b560-11e6-9514-13623bb59def.PNG)

**Comment by HookyQR** [comment] 2016-11-28 17:29
@sqnkov, you need to put `"editor.formatOnSave": true` back into your settings. `"beautify.onSave"` is out again. (As it was in 0.6.0) Sorry for the mess around.

**Comment by HookyQR** [comment] 2016-11-28 17:32
Duplicate of #58.

**Comment by sqnkov** [comment] 2016-11-28 17:33
@HookyQR , all good now. I was looking up Your initial advice, sorry for that.

**Comment by HookyQR** [comment] 2016-11-28 17:34
No problem, I'm here to help.

**Closed by HookyQR** 2016-11-28 17:34 UTC
