### ISSUE TITLE
[request] indent and line break text nodes

### ISSUE THREAD

**Issue by SamSlate** [HookyQR/VSCodeBeautify#118] opened 2017-03-07 19:24 UTC
`<p>some text</p>` 

would become 

`<p>`
&nbsp;&nbsp;&nbsp;&nbsp;`some text`
`</p>`

same for h1, and other elements with text nodes. *pretty please!*

**Comment by 5achinJani** [comment] 2017-03-08 14:14
Possible duplicate of [#109](https://github.com/HookyQR/VSCodeBeautify/issues/109)

**Comment by HookyQR** [comment] 2017-05-31 12:15
Closed as duplicate of #109

**Closed by HookyQR** 2017-05-31 12:15 UTC
