### ISSUE TITLE
Formatting grid-template to single line

### ISSUE THREAD

**Issue by basickarl** [HookyQR/VSCodeBeautify#301] opened 2019-04-05 13:38 UTC
Currently formats the following grid-template code to one line in .scss files:
```
    grid-template:
        [row1-start] "header header header"25px [row1-end] 
        [row2-start] "footer footer footer"25px [row2-end] 
        / auto 50px auto;
```

**Comment by HookyQR** [comment] 2019-04-30 11:27
Duplicate of #234.
Not currently supported by js-beautify. Won't get supported (probably) till it has been accepted into the standard.

**Closed as completed by HookyQR** 2019-04-30 11:27 UTC
Labels: duplicate, js-beautify (upstream), css
