### ISSUE TITLE
object in object, extra spaces added before first line in brace

### ISSUE THREAD

**Issue by RobinQian001** [HookyQR/VSCodeBeautify#273] opened 2018-10-09 08:38 UTC
* **Operating System (+Version)**: OS X El Capitan 10.11.6
* **VS Code Version**: 1.28.0
* **beautify Version**: 1.4.4

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

VS Code:
```javascript
{
  "files.autoSave": "off",
  "editor.fontSize": 14,
  "editor.tabSize": 2,
  "editor.cursorStyle": "line",
  "editor.insertSpaces": false,
  "emmet.triggerExpansionOnTab": true,
  "explorer.openEditors.visible": 9,
  "window.zoomLevel": 0,
  "explorer.autoReveal": false,
  "telemetry.enableTelemetry": false,
  "telemetry.enableCrashReporter": false,
  "files.associations": {
    "*.vue": "vue"
  },
  "editor.wordWrap": "off",
  "editor.wordWrapColumn": 80,
  "editor.minimap.enabled": true,
  "git.confirmSync": false,
  "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": true
  },
  "editor.formatOnPaste": false,
  "editor.dragAndDrop": true,
  "scss.lint.duplicateProperties": "warning",
  "scss.lint.emptyRules": "ignore",
  "workbench.colorTheme": "One Dark Pro",
  "vsicons.presets.jsOfficial": true,
  "editor.tabCompletion": true,
  "editor.useTabStops": false,
  "editor.trimAutoWhitespace": true,
  "workbench.iconTheme": "vscode-icons",
  "workbench.startupEditor": "newUntitledFile",
  "typescript.npm": null,
  "terminal.external.osxExec": "Terminal.app",
  "terminal.integrated.shell.osx": "/bin/zsh",
  "fileheader.LastModifiedBy": "Robin",
  "fileheader.Author": "Robin",
  "typescript.check.npmIsInstalled": false,
  "python.formatting.provider": "yapf",
  "javascript.implicitProjectConfig.experimentalDecorators": true,
  "[javascript]": {},
  "git.autofetch": true,
  "gitlens.advanced.messages": {
    "suppressCommitHasNoPreviousCommitWarning": false,
    "suppressCommitNotFoundWarning": false,
    "suppressFileNotUnderSourceControlWarning": false,
    "suppressGitVersionWarning": false,
    "suppressLineUncommittedWarning": false,
    "suppressNoRepositoryWarning": false,
    "suppressResultsExplorerNotice": false,
    "suppressShowKeyBindingsNotice": true,
    "suppressUpdateNotice": true,
    "suppressWelcomeNotice": false
  },
  "extensions.ignoreRecommendations": false,
  "explorer.confirmDragAndDrop": false,
  "gitlens.keymap": "alternate",
  "editor.formatOnSave": true,
  "beautify.config": {
    "indent_with_tabs": false,
    "space_before_conditional": false,
    "space_in_paren": true,
    "indent_size": 2,
    "indent_char": " ",
    "space_after_anon_function": true,
    "keep_function_indentation": true
  },
  "beautify.language": {
    "js": {
      "type": [
        "javascript",
        "json",
        "jsonc"
      ],
      "filename": [
        ".jshintrc",
        ".jsbeautifyrc"
      ]
    },
    "css": [
      "css",
      "scss",
      "less"
    ],
    "html": [
      "htm",
      "html",
      "vue"
    ]
  },
  "beautify.ignore": [
  ],
  "editor.acceptSuggestionOnCommitCharacter": false,
  "debug.inlineValues": true,
  "gitlens.historyExplorer.enabled": true,
  "gitlens.gitExplorer.files.layout": "auto",
  "terminal.integrated.rendererType": "dom",
  "workbench.colorCustomizations": {
    "activityBarBadge.background": "#2979FF",
    "list.activeSelectionForeground": "#2979FF",
    "list.inactiveSelectionForeground": "#2979FF",
    "list.highlightForeground": "#2979FF",
    "scrollbarSlider.activeBackground": "#2979FF50",
    "editorSuggestWidget.highlightForeground": "#2979FF",
    "textLink.foreground": "#2979FF",
    "progressBar.background": "#2979FF",
    "pickerGroup.foreground": "#2979FF",
    "tab.activeBorder": "#2979FF",
    "notificationLink.foreground": "#2979FF",
    "editorWidget.resizeBorder": "#2979FF",
    "editorWidget.border": "#2979FF",
    "settings.modifiedItemIndicator": "#2979FF",
    "settings.headerForeground": "#2979FF",
    "panelTitle.activeBorder": "#2979FF",
    "breadcrumb.activeSelectionForeground": "#2979FF",
    "menu.selectionForeground": "#2979FF",
    "menubar.selectionForeground": "#2979FF"
  }
}
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command
```javascript
module.exports = {

  getAvgSalary: async ctx => {
      try {
        let {
          industry_code,
          city_code,
          scale_code,
          nature_code,
          education_code,
          experience_code,
          job_code
        } = ctx.query;

        let predictService = new PredictService( ctx );
        let data = await predictService.getJobAvgOrSort( {
          industry_code,
          city_code,
          scale_code,
          nature_code,
          job_code
        } );

        pr.success( ctx, data[ 0 ] );
      } catch ( error ) {
        pr.error( ctx, error );
      }
    }
}
```

## Expected results
```javascript
module.exports = {

  getAvgSalary: async ctx => {
    try {
      let {
        industry_code,
        city_code,
        scale_code,
        nature_code,
        education_code,
        experience_code,
        job_code
      } = ctx.query;

      let predictService = new PredictService( ctx );
      let data = await predictService.getJobAvgOrSort( {
        industry_code,
        city_code,
        scale_code,
        nature_code,
        job_code
      } );

      pr.success( ctx, data[ 0 ] );
    } catch ( error ) {
      pr.error( ctx, error );
    }
  }
}
```

## Actual results
Details of what happened ...
_provide example (actual) output_

**Comment by HookyQR** [comment] 2018-10-17 06:56
Looks like it's caused by the `async`. Fixed in 1.4.5 (preparing release now)

**Closed** 2018-10-24 08:39 UTC
