### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by notte** [HookyQR/VSCodeBeautify#305] opened 2019-04-28 11:07 UTC
- Issue Type: `Performance`
- Extension Name: `beautify`
- Extension Version: `1.4.11`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/YAO/HookyQR.beautify-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by HookyQR** [comment] 2019-04-29 03:57
:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/YAO/HookyQR.beautify-unresponsive.cpuprofile.txt`

**Comment by HookyQR** [comment] 2019-04-30 11:35
Duplicate of #300

**Closed as completed by HookyQR** 2019-04-30 11:35 UTC
