### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by pkoolc1** [HookyQR/VSCodeBeautify#303] opened 2019-04-16 09:50 UTC
- Issue Type: `Performance`
- Extension Name: `beautify`
- Extension Version: `1.4.11`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/paul/HookyQR.beautify-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by HookyQR** [comment] 2019-04-30 11:18
Duplicate of #300

**Closed as completed** 2019-04-30 11:17 UTC
