### ISSUE TITLE
CSS选择器被删除了

### ISSUE THREAD

**Issue by JackFGreen** [HookyQR/VSCodeBeautify#108] opened 2017-02-22 09:41 UTC
* **Operating System (+Version)**: OS X 10.10.5 (14F2009)
* **VS Code Version**:  1.9.1
* **beautify Version**: 0.8.7

格式化的时候 CSS 选择器被删除了
- 选择器只有一个字符，例：a，p
- 选择器前面有空行
- 在 .vue 文件中

**before**
![2f6608b1-9455-4be8-ad67-2ff08343a95d](https://cloud.githubusercontent.com/assets/23187848/23205523/2371965a-f925-11e6-89ae-fcf647678fdd.png)

**after**
![54ea3fc5-5e0e-4cef-99af-245f31a6e101](https://cloud.githubusercontent.com/assets/23187848/23205569/4fdc7b38-f925-11e6-89e8-3e2550760b2d.png)

**Comment by HookyQR** [comment] 2017-02-22 19:54
This is caused by `preserve_newlines`. You can work around this by removing `preserve_newlines` from your settings.

Working on a fix for this now.

**Closed** 2017-05-30 08:50 UTC
