### ISSUE TITLE
Javascript in <script> tags in an html file is not being formatted

### ISSUE THREAD

**Issue by renzska** [HookyQR/VSCodeBeautify#77] opened 2016-12-08 16:24 UTC
* **Operating System (+Version)**: Mac OS Sierra 10.12.11
* **VS Code Version**: 1.7.2
* **beautify Version**: Latest

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)

Defaults

## Action performed
Format html file that has javascript inside <script> tag with `HookyQR.beautifyFile` command

```
<script>
   function getListItems(listName) {
                                    return $.ajax({
            url: "/site/peak/_api/web/lists/getbytitle('" + listName + "')/items",
                        method: "GET",
            headers: { "Accept": "application/json; odata=nometadata" },
        });
    }
</script>

<div class="col-xs-3">
    <a href="javascript:getListItems('Categories');" class="btn btn-block btn-lg btn-success"><i class="fa fa-calendar-plus-o fa-fw"></i> Get Categories</a>
</div>
<div class="col-xs-3">
    <a href="javascript:getListItems('Instructors');" class="btn btn-block btn-lg btn-success"><i class="fa fa-calendar-plus-o fa-fw"></i> Get Instructors</a>
</div>
<br />
<div id="categories"></div>
<br /><br />
<div id="instructors"></div>
```

## Expected results

I expected the javascript inside the script tag to be formatted like the below example:

```
<script>
   function getListItems(listName) {
      return $.ajax({
            url: "/site/peak/_api/web/lists/getbytitle('" + listName + "')/items",
            method: "GET",
            headers: { "Accept": "application/json; odata=nometadata" },
        });
    }
</script>

<div class="col-xs-3">
    <a href="javascript:getListItems('Categories');" class="btn btn-block btn-lg btn-success"><i class="fa fa-calendar-plus-o fa-fw"></i> Get Categories</a>
</div>
<div class="col-xs-3">
    <a href="javascript:getListItems('Instructors');" class="btn btn-block btn-lg btn-success"><i class="fa fa-calendar-plus-o fa-fw"></i> Get Instructors</a>
</div>
<br />
<div id="categories"></div>
<br /><br />
<div id="instructors"></div>
```

## Actual results

The javascript was not formatted.

**Comment by skirsten** [comment] 2016-12-10 15:59
Thank you for proving that this is a bug. I just spend an hour trying to figure out why I am the only person on this planet where the `<script>` tags are not getting formatted.

This issue should be marked critical as this brakes one of the main functionalities of a code beautifier.

**Comment by HookyQR** [comment] 2016-12-10 19:25
Hey there. It's not a bug, it's caused by an unfortunate default setting in VS Code:
```
"html.format.unformatted": 
    "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, 
        em, i, img, input, kbd, label, map, object, q, samp, script, 
        select, small, span, strong, sub, sup, textarea, tt, var"
```
If you remove `script` from this setting it will work as you expected.

**Comment by HookyQR** [comment] 2016-12-10 19:34
You'll be happy to know that the `script` tag is being removed from this default *eventually*. See  https://github.com/Microsoft/vscode/commit/8eb0cce43838ea8531c1bce8f44d835d9c2060d5

**Comment by skirsten** [comment] 2016-12-10 19:51
Wow, thank you very much for this fast answer and the fix. I actually suspected some config having `script` excluded as default, but couldn't find one. Thank you for this awesome project!

**Comment by HookyQR** [comment] 2017-01-03 23:16
This should be fixed in the current VS Code version. `script` has been removed from the default for `unformatted`.

**Closed** 2017-01-05 18:53 UTC
Labels: VS Code
